import dotenv from 'dotenv'
dotenv.config({
    path: './.env'
})

const {
    NODE_ENV,
    ACCESS_TOKEN_EXPIREIN,
    ACCESS_TOKEN_SECRET,
    STRIPE_WEBHOOK_SECRET,
    MONGO_URL,
    SERVER_URL,
    PASS_SECRET,
    JWT_SECRET,
    PORT,
    EMAIL,
    PASSWORD,
    CORS_ORIGIN,
    STRIPE_KEY,
    ACCESS_TOKEN_LONG_EXPIREIN,
    REDIS_HOST,
    REDIS_PASSWORD,
    REDIS_PORT,
    CLIENT_URL,
    DATABASE_URL,

    KEYCLOAK_CLIENT_ID,
    BACKEND_URL,
    KEYCLOAK_CLIENT_SECRET,
    KEYCLOAK_ISSUER_URL,
    KEYCLOAK_AUTHORIZATION_URL,
    KEYCLOAK_TOKEN_ENDPOINT,
    KEYCLOAK_USER_INFO_URL,
    KEYCLOAK_SESSION_ENDPOINT,
    FRONTEND_URL,
    REDIRECT_URL
} = process.env

const ALLOWED_ORIGINS = process.env.ALLOWED_ORIGINS ? process.env.ALLOWED_ORIGINS.split(',') : []

const SWAGGER_STAGE_URL = NODE_ENV === 'production' ? SERVER_URL : `http://localhost:${PORT}`

export {
  ACCESS_TOKEN_EXPIREIN, ACCESS_TOKEN_LONG_EXPIREIN, ACCESS_TOKEN_SECRET, ALLOWED_ORIGINS, BACKEND_URL, CLIENT_URL, CORS_ORIGIN, DATABASE_URL, EMAIL, FRONTEND_URL, JWT_SECRET, KEYCLOAK_AUTHORIZATION_URL, KEYCLOAK_CLIENT_ID,
  KEYCLOAK_CLIENT_SECRET, KEYCLOAK_ISSUER_URL, KEYCLOAK_SESSION_ENDPOINT, KEYCLOAK_TOKEN_ENDPOINT,
  KEYCLOAK_USER_INFO_URL, MONGO_URL, NODE_ENV, PASS_SECRET, PASSWORD, PORT, REDIRECT_URL, REDIS_HOST,
  REDIS_PASSWORD,
  REDIS_PORT, STRIPE_KEY,
  STRIPE_WEBHOOK_SECRET, SWAGGER_STAGE_URL
}

